### ISSUE TITLE
It's possible to have html instead string label

### ISSUE THREAD

**Issue by nseb** [pepstock-org/Charba#10]
Hi,
I would like replace Label String by Icon with this code HTML ('<p class=\"lead\"><span class=\"flag-icon flag-icon-" + natioCountryCountry.getAlpha2() + "\"></span></p>), it's possible ?

![image](https://user-images.githubusercontent.com/6363226/43552841-81090e46-95ec-11e8-96d9-0445276fc3c1.png)

**Comment by stockiNail** [comment]
Hi,  html labels are not supported in CHARTJS (and therefore in Charba as well) since everything is done on the canvas.
If you're using an icon font you should be able to set the font family to the icon font, by FontFamily methods.

I'm gonna do some tests as well.

**Comment by nseb** [comment]
shame, I do not use a real font, but a style css. I could see if I find a glyph make for the flags

**Comment by stockiNail** [comment]
In Charba is still missing [a feature of Chart.js](http://www.chartjs.org/docs/latest/developers/axes.html) to create custom axes. :(
I'm gonna implement it as soon as possible.
My goal is to provide an interface that you can implement and register it as new Axes.

**Comment by stockiNail** [comment]
@nseb what do you think?

Done by Charba, with some new features, leveraging on plugin.

![canvasflags](https://user-images.githubusercontent.com/11741250/44524021-4971a280-a6dc-11e8-803c-9a02ad9a7535.png)

**Comment by stockiNail** [comment]
We are still refactoring the "items" part (to read info from CHART.JS instance) right now... Can you wait some days?

**Comment by nseb** [comment]
Yes , no problems ;-)

**Comment by nseb** [comment]
Thanks! I will try as soon as possible

**Comment by stockiNail** [comment]
@nseb first of all we have published new version 1.5.

If you copy and paste the source I published here, you have the code of plugin and the activation at chart level.

chart.getPlugins ().add (p) is the statement to activate it.

FYI we have also updated the wiki where we are explaining how to use Charba, plugins as well

**Comment by nseb** [comment]
Thanks

**Comment by nseb** [comment]
I testing, the code is called , but nothing is draw ?
In wiki this line not working :  chart.getPlugins().setEnabled("pluginid", true);

**Comment by nseb** [comment]
I understand , I have negative X and add :  chart.getOptions().getLayout().getPadding().setLeft(100);
But always no image draw

**Comment by stockiNail** [comment]
Yes, you should. I usually use ImageResource of Gwt.

I suggest to use onAfterDatasetsDraw

**Comment by stockiNail** [comment]
Maybe can help.
See the [class](https://github.com/pepstock-org/Charba-Showcase/blob/master/src/org/pepstock/charba/showcase/client/samples/HorizontalFlagsBarView.java) in the showcase project related to flags and we managed images.

**Comment by nseb** [comment]
my code works, I test with a lot of countries with the application on a phone to see the rendering and I shared the result

**Comment by stockiNail** [comment]
Very good!

**Comment by nseb** [comment]
I have a smalll enhancement. I'm trying to make the code more responsive, for tablet and mobile by reducing the padding too much:

`
 @Override
        public boolean onBeforeLayout(AbstractChart<?, ?> chart, JavaScriptObject options) {
            boolean b = super.onBeforeLayout(chart, options);
            if (chart.getContainer().getOffsetWidth() > 450) {
                chart.getOptions().getLayout().getPadding().setLeft((50));
            } else {
                chart.getOptions().getLayout().getPadding().setLeft(25);
            }
            return b;
        }
`

But the event onBeforeLayout, is not the most suitable, if I resize the screen (= change orientation tablet), this code is not called

**Comment by stockiNail** [comment]
@nseb CHART.JS uses the options during the init phase to calculate the sizes for all component. Changing the padding in the plugin, you don't affect the already calculated sizes.
To be able to change padding using options you need to redraw the chart itself.
Let me take some time to propose you a solution.

**Comment by nseb** [comment]
@Thanks for your reply.
For the moment I fixed flag image size : https://www.ukart.io/#!/events/70

**Comment by stockiNail** [comment]
Well, let me say that was a little complex to address your need, because of:

 1. the padding is absolute value and not related to size of chart or any other element ot it	
 1. changing otpions into a plugin doesn't have any effect on CHART.JS
 1. changing option you need to redraw the chart (not only update)

First of all, in my example instead of using padding of the chart, you used the padding of `ScaleLabel` of axis, activating it. The label to show has been set to blank.
To do that, I created a axis (in the constructor or my composite) and set to chart (as `YAxes` because I'm in HorizontalBar chart), as following:

```java
axis = new CartesianCategoryAxis(chart);
axis.setDisplay(true);
axis.getScaleLabel().setDisplay(true);

chart.getOptions().getScales().setYAxes(axis);
```   

As you can see I didn't set any padding because I wanted to calculate at runtime before chart will be drawn. The axis instance has been set as a field of my composite, as following:

```java
public class HorizontalFlagsBarView extends BaseComposite{
	
	private static ViewUiBinder uiBinder = GWT.create(ViewUiBinder.class);

	interface ViewUiBinder extends UiBinder<Widget, HorizontalFlagsBarView> {
	}
	
	@UiField
	BarChart chart;
	
	CartesianCategoryAxis axis;
```   

To set the padding before chart drawing and to be sure having the width of the chart (maintaining it responsive, that means without setting width or height to canvas), I overrided the `onAttach` method of the composite, 
which contains the chart. In this way I'm setting a options BEFORE chart is started and therefore it can used the right amount of padding.

```java
@Override
protected void onAttach() {
	calculateAndSetScaleLabelPadding(chart.getCanvas().getParentElement().getOffsetWidth());
	super.onAttach();
}
```   

In the method, I got the canvas, and then its parent and got the width by `getOffsetWidth` of canvas parent.
With the width, I'm callig my method `calculateAndSetScaleLabelPadding` to calculate a proportional padding based on size of chart:
 
```java
private void calculateAndSetScaleLabelPadding(int width) {
	int percent = width * PERCENT / 100;
	int padding = Math.min(Math.max(MIN, percent), MAX);
	axis.getScaleLabel().getPadding().setTop(padding);
}
```

To be very responsive, we should calculate the size of padding as percentage of real width of chart, with MIN and MAX.
For this reason, I set some constants:

```java
	private static final int MIN = 50;
	
	private static final int MAX = 100;
	
	private static final int PERCENT = 10;
```

In my example, the padding is 10% of total width, with MIN of 50px and MAX of 100px.

Below the new method of plugin with new calculation and drawing of flags:

```java
@Override
public void onAfterDatasetsDraw(AbstractChart<?, ?> chart, double easing, JavaScriptObject options) {
	final int padding = 4;
	
	Context2d ctx = chart.getCanvas().getContext2d();
	ScaleItem scale = chart.getChartNode().getScales().getItems().get(ScalesNode.DEFAULT_Y_AXIS_ID);
	List<String> ticks = scale.getTicks();
	
	int heightAmongLabels = (scale.getBottom() - scale.getTop()) / ticks.size();
	final int height = Math.min(heightAmongLabels - (padding * 2), MIN);
	final int width = Math.min(60 * height / 40, axis.getScaleLabel().getPadding().getTop() - padding);
		
	int x = scale.getLeft() + axis.getScaleLabel().getPadding().getTop() - width + axis.getScaleLabel().getFontSize();
	int y = scale.getTop();

	for (String tick : ticks) {
		ImageElement image = null;
		if (tick.equalsIgnoreCase("br")) {
			image = getImageElement(Images.INSTANCE.flagBR());
		} else if (tick.equalsIgnoreCase("de")) {
			image = getImageElement(Images.INSTANCE.flagDE());
		} else if (tick.equalsIgnoreCase("fr")) {
			image = getImageElement(Images.INSTANCE.flagFR());
		} else if (tick.equalsIgnoreCase("gb")) {
			image = getImageElement(Images.INSTANCE.flagGB());
		} else if (tick.equalsIgnoreCase("it")) {
			image = getImageElement(Images.INSTANCE.flagIT());
		} else if (tick.equalsIgnoreCase("us")) {
			image = getImageElement(Images.INSTANCE.flagUS());
		}
		if (image != null) {
			int yToDraw = y + (heightAmongLabels - height) / 2;
			ctx.drawImage(image, x, yToDraw, width, height);
		}
		y = y + heightAmongLabels;
	}
}
```

![first](https://user-images.githubusercontent.com/11741250/44912979-24101480-ad2c-11e8-9cd1-1199287dbe4b.png)

That's not enough, because we should take care of resize as well.

Therefore I added a resize handler to catch resize events. But when you are resizing, the handler can receive many events and you don't have any information when the event is last one.
I added a GWT timer which will calculate new padding (based on the size of the chart) only for the last event (waiting for 500ms).
Being the chart already intitialized and I'm changing a option, the timer will redraw the chart in order to be able to use the right padding.

```java
chart.addHandler(new ChartResizeEventHandler() {

	private final Timer t = new Timer() {
		@Override
		public void run() {
			chart.reset();
			chart.draw();
		}
	};
		
	@Override
	public void onResize(final ChartResizeEvent event) {
		int width = event.getSize().getWidth();
		calculateAndSetScaleLabelPadding(width);
		t.schedule(500);
	}
}, ChartResizeEvent.TYPE);
```

![resized](https://user-images.githubusercontent.com/11741250/44912999-30946d00-ad2c-11e8-836d-afe0c20f1bb0.png)

Attached here the whole source.


```java
package org.pepstock.charba.showcase.client.samples;

import java.util.List;

import org.pepstock.charba.client.AbstractChart;
import org.pepstock.charba.client.BarChart;
import org.pepstock.charba.client.colors.IsColor;
import org.pepstock.charba.client.data.BarDataset;
import org.pepstock.charba.client.data.Dataset;
import org.pepstock.charba.client.enums.Position;
import org.pepstock.charba.client.events.ChartResizeEvent;
import org.pepstock.charba.client.events.ChartResizeEventHandler;
import org.pepstock.charba.client.items.ScaleItem;
import org.pepstock.charba.client.items.ScalesNode;
import org.pepstock.charba.client.options.scales.CartesianCategoryAxis;
import org.pepstock.charba.client.plugins.AbstractPlugin;
import org.pepstock.charba.client.plugins.InvalidPluginIdException;
import org.pepstock.charba.showcase.client.resources.Images;
import org.pepstock.charba.showcase.client.samples.Toast.Level;

import com.google.gwt.canvas.dom.client.Context2d;
import com.google.gwt.core.client.GWT;
import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.dom.client.ImageElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.resources.client.ImageResource;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Timer;
import com.google.gwt.user.client.ui.Image;
import com.google.gwt.user.client.ui.Widget;


/**

 * @author Andrea "Stock" Stocchero
 */
public class HorizontalFlagsBarView extends BaseComposite{
	
	private static ViewUiBinder uiBinder = GWT.create(ViewUiBinder.class);

	private static final String[] COUNTRIES = {"br","de","fr","gb","it","us"};
	
	interface ViewUiBinder extends UiBinder<Widget, HorizontalFlagsBarView> {
	}
	
	@UiField
	BarChart chart;
	
	CartesianCategoryAxis axis;
	
	private static final int MIN = 50;
	
	private static final int MAX = 100;
	
	private static final int PERCENT = 10;
	
	public HorizontalFlagsBarView() {
		initWidget(uiBinder.createAndBindUi(this));
		chart.getOptions().setResponsive(true);
		chart.getOptions().getLegend().setPosition(Position.right);
		chart.getOptions().getTitle().setDisplay(true);
		chart.getOptions().getTitle().setText("Charba Horizontal Bar Chart with Flags");
		
		BarDataset dataset1 = chart.newDataset();
		dataset1.setLabel("Countries");
		
		IsColor color1 = Colors.ALL[0];
		
		dataset1.setBackgroundColor(color1.alpha(0.2));
		dataset1.setBorderColor(color1.toHex());
		dataset1.setBorderWidth(1);
		dataset1.setData(getRandomDigits(COUNTRIES.length, false));

		axis = new CartesianCategoryAxis(chart);
		axis.setDisplay(true);
		axis.getScaleLabel().setDisplay(true);

		chart.getData().setLabels(COUNTRIES);
		chart.getData().setDatasets(dataset1);

		chart.getOptions().getScales().setYAxes(axis);
		
		chart.addHandler(new ChartResizeEventHandler() {

			private final Timer t = new Timer() {
				@Override
				public void run() {
					chart.reset();
					chart.draw();
				}
			};

			
			@Override
			public void onResize(final ChartResizeEvent event) {
				int width = event.getSize().getWidth();
				calculateAndSetScaleLabelPadding(width);
				t.schedule(500);
			}
		}, ChartResizeEvent.TYPE);
		
		AbstractPlugin p = new AbstractPlugin() {
			
			@Override
			public String getId() {
				return "test";
			}

			/* (non-Javadoc)
			 * @see org.pepstock.charba.client.plugins.AbstractPlugin#onAfterDatasetsDraw(org.pepstock.charba.client.AbstractChart, double)
			 */
			@Override
			public void onAfterDatasetsDraw(AbstractChart<?, ?> chart, double easing, JavaScriptObject options) {
				final int padding = 4;
				Context2d ctx = chart.getCanvas().getContext2d();
				ScaleItem scale = chart.getChartNode().getScales().getItems().get(ScalesNode.DEFAULT_Y_AXIS_ID);
				List<String> ticks = scale.getTicks();
				int heightAmongLabels = (scale.getBottom() - scale.getTop()) / ticks.size();
				final int height = Math.min(heightAmongLabels - (padding * 2), MIN);
				final int width = Math.min(60 * height / 40, axis.getScaleLabel().getPadding().getTop() - padding);
				int x = scale.getLeft() + axis.getScaleLabel().getPadding().getTop() - width + axis.getScaleLabel().getFontSize();
				int y = scale.getTop();
				for (String tick : ticks) {
					ImageElement image = null;
					if (tick.equalsIgnoreCase("br")) {
						image = getImageElement(Images.INSTANCE.flagBR());
					} else if (tick.equalsIgnoreCase("de")) {
						image = getImageElement(Images.INSTANCE.flagDE());
					} else if (tick.equalsIgnoreCase("fr")) {
						image = getImageElement(Images.INSTANCE.flagFR());
					} else if (tick.equalsIgnoreCase("gb")) {
						image = getImageElement(Images.INSTANCE.flagGB());
					} else if (tick.equalsIgnoreCase("it")) {
						image = getImageElement(Images.INSTANCE.flagIT());
					} else if (tick.equalsIgnoreCase("us")) {
						image = getImageElement(Images.INSTANCE.flagUS());
					}

					if (image != null) {
						int yToDraw = y + (heightAmongLabels - height) / 2;
						ctx.drawImage(image, x, yToDraw, width, height);
					}
					y = y + heightAmongLabels;
				}
			}
		};
		try {
			chart.getPlugins().add(p);
		} catch (InvalidPluginIdException e) {
			new Toast("Invalid PlugiID!", Level.ERROR, e.getMessage()).show();
		}
	
	}
	
	/* (non-Javadoc)
	 * @see com.google.gwt.user.client.ui.Composite#onAttach()
	 */
	@Override
	protected void onAttach() {
		calculateAndSetScaleLabelPadding(chart.getCanvas().getParentElement().getOffsetWidth());
		super.onAttach();
	}

	private ImageElement getImageElement(ImageResource resource) {
		Image img = new Image(resource.getSafeUri());
	    return ImageElement.as(img.getElement());
	}

	@UiHandler("randomize")
	protected void handleRandomize(ClickEvent event) {
		for (Dataset dataset : chart.getData().getDatasets()){
			dataset.setData(getRandomDigits(months));
		}
		chart.update();
	}
	
	private void calculateAndSetScaleLabelPadding(int width) {
		int percent = width * PERCENT / 100;
		int padding = Math.min(Math.max(MIN, percent), MAX);
		axis.getScaleLabel().getPadding().setTop(padding);
	}
}
```

**Comment by stockiNail** [comment]
@nseb I'd like to inform you in advance that as promised we are developing the extensions of CHART.JS about custom charts (based on [controllers](http://www.chartjs.org/docs/latest/developers/charts.html)).

With this feature, all above code can be move into a controller, without adding `onAttach` extension and `Resize` listener.

As usual, please wait for some days because we are completing tests.

**Comment by nseb** [comment]
@stockiNail  , Thanks , sorry I had time to reply at your previous comment.
