### ISSUE TITLE
Cartesian Linear Axes documentation correction needed

### ISSUE THREAD

**Issue by naabers2** [pepstock-org/Charba#102]
Hello,

I believe the 'Cartesian Linear Axes' documentation needs a minor correction that will certainly help newbies like me get off to a good start.

**URL:**
https://pepstock-org.github.io/Charba-Wiki/docs/axes/CartesianLinearAxes/

**Change from:**

// adds axes to chart configuration
chart.getOptions().setAxes(axis1, ...);

**to:**

// adds axes to chart configuration
chart.getOptions().getScales().setAxes(axis1,...);

Thanks for this great GWT Wrapper!

--John

**Comment by stockiNail** [comment]
@naabers2 Good catch! Thank you! I'm going to fix it asap.

> Thanks for this great GWT Wrapper!

Happy to read it! ;)

**Comment by naabers2** [comment]
Great! Thanks :)

**Comment by stockiNail** [comment]
Doc has been fixed on main: https://github.com/pepstock-org/Charba-Wiki/commit/a9ac43720fb30793acba3fdf83cd24f7f0dd3f86

Available in wiki site in next version.

Thanks a lot again
