### ISSUE TITLE
DataLabelsPlugin weird behaviour on stacked bar chart with multiple labels

### ISSUE THREAD

**Issue by AHijner** [pepstock-org/Charba#105]
Hi! 
We're using some Charba charts for our new dashboard. One of the charts we are making is a stacked-bar-chart with two dataset. We want to use data labels for both of these data sets, but each will have a different position. It's working very nicely except for one small detail that we cannot make sense of. One of the two labels also results in a black spot at the top of the chart:
![image](https://github.com/user-attachments/assets/7c70ccb7-3678-40a9-963f-5a796fa16586)

If i hide the 'minimale'-dataset, the spot dissappears. If I don't set this datalabel in the code it dissappears. If i make the datalabel longer with some text, the black-thing will also become longer like so:
![image](https://github.com/user-attachments/assets/f1625bda-21ac-4fb0-8a81-262f704c1216)

Changing anything on the 'netto'-dataset has no effect whatsoever (or even removing it). The code for both labels is very similar, even when brought back to its basics without any layout-settings, the behaviour persists.

The simplest code, where the issue still presents itself, where '1' is the correctly-working net-dataset and '2' is the min-data set with weird black dot:
```
DataLabelsOptionsBuilder builder = DataLabelsOptionsBuilder.create();
        builder.createLabel("1")
                .setFormatter((context, dataItem) -> {
                    if (context.getDatasetIndex() == 0) {
                        return "";
                    }
                    return "1";
                }).getOptionsBuilder();
        builder.createLabel("2")
                .setFormatter((context, dataItem) -> {
                    if (context.getDatasetIndex() == 1) {
                        return "";
                    }
                    return "2";
                }).getOptionsBuilder();
        getOptions().getPlugins().setOptions(DataLabelsPlugin.ID, builder.build());
```

So it seems a very strange issue to us. Perhaps we are missing something obvious. Are we mis-using the datalabels plugin somehow? The chart incl datalabels are otherwise working very well!

Do you have an idea what could cause this and if we can fix it?
Let me know if you need any more code or other information!

Kind regards,
Annemijn

**Comment by stockiNail** [comment]
@AHijner this should be a normal behavior of datalabels plugin where the data at a specific index is `NaN` or `null`.  

Could you share the datasets options?

**Comment by AHijner** [comment]
Ah yes, that makes sense!
With this hint we found the problem. We had a request to make the y-axis slightly higher than te max value, so we set:
```
yAxis.setSuggestedMax(context -> {
            List<Double> data = context.getChart().getData().getDatasets().get(0).getData(); //min
            data.addAll( context.getChart().getData().getDatasets().get(1).getData()); //net
            return Math.max(5 + data.stream().max(Double::compare).orElse(0D), 15);
        });
```
Which of course will add the extra data-points to the first set. Silly mistake.
With something like 
```
yAxis.setSuggestedMax(context -> {
            List<Double> minData = context.getChart().getData().getDatasets().get(0).getData(); //min
            List<Double> singletonData = context.getChart().getData().getDatasets().get(1).getData(); //net
            return Math.max(5 +
                   Stream.concat(minData.stream(), singletonData.stream())
                    .max(Double::compare).orElse(0D), 15);
        });
```
the problem is fixed!

Thank you so much for the input, it was very helpful! :)
