### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by nseb** [pepstock-org/Charba#11]
Hi,

it's possible to have legend in left like this :

![image](https://user-images.githubusercontent.com/6363226/43770635-409cd6c6-9a3d-11e8-810e-8dc2cc0d5b76.png)

**Comment by stockiNail** [comment]
@nseb the legend can be located into top, bottom, right and left. But it's not part of axes, as you drawed

**Comment by nseb** [comment]
My result :-(, I create in issue enhancement in chart.js ?
![image](https://user-images.githubusercontent.com/6363226/43788107-e5cecbfc-9a6c-11e8-951f-bfa1652a21cd.png)

**Comment by stockiNail** [comment]
@nseb yes you can. Seeing your first sample, why don't to have something like that ?

![updatechart](https://user-images.githubusercontent.com/11741250/43951126-8cc2692e-9c92-11e8-95f0-46d7c2a8c07a.png)

**Comment by stockiNail** [comment]
@nseb What do you think? Close to what you are looking for?

Bone by Charba with a TickCallback and a puglin.

![canvasstandings](https://user-images.githubusercontent.com/11741250/44572554-6cf02800-a784-11e8-95bb-2b577e3bc6f5.png)

**Comment by nseb** [comment]
exactly, did you develop an extension?

Look what I did, tab stats, thanks for watching on a tablet or mobile, because verson pc I did not work the style:
https://www.ukart.io/#!/race/183/run/2318

**Comment by stockiNail** [comment]
Not really an extension. I'm adding the capabilitty to get all information from CHART JS instance (for instance the size of boxes, like legends, axis and so on). With this data and using a plugins, I can draw into canvas whatever and wherever I want.

I'm gonna have a look. We are developing something similar (as dashboard) on GWT MAterial but we didn't have those behaviours

**Comment by nseb** [comment]
therefore, it makes a lot of code to do this dashbard if you redraw everything, right?

**Comment by stockiNail** [comment]
well, if you redraw everything, you could have effort to do it. What are you using as base components for your dashboard? MaterialMasonry?

**Comment by nseb** [comment]
MaterialMasonry -> MaterialColumn->MaterialCard (with chart in MaterialCardImage).

**Comment by nseb** [comment]
@stockiNail  , you can share your code example to realize if that will not make my app heavier?

**Comment by stockiNail** [comment]
@nseb sorry but that application  is not open source and I can not.

**Comment by nseb** [comment]
@stockiNail  , no problems I understand

**Comment by stockiNail** [comment]
@nseb here are the instructions to have the chart as  above described.

Set padding on top and right to be able to have space to write the "values" on right part of chart and disable the legend.

```java
chart.getOptions().getLegend().setDisplay(false);
chart.getOptions().getLayout().getPadding().setTop(40);
chart.getOptions().getLayout().getPadding().setRight(40);
```
The values to put on AXIS, you could set the label of each datasets with the tick to put into axis.

```java
dataset.setLabel(TICKS[i]);
```

Then you can create an axis setting the "reverse"to true and adding a tickcallback in order to put the dataset labels as ticks of axis:

```java
CartesianLinearAxis axis2 = new CartesianLinearAxis(chart);
axis2.setDisplay(true);
axis2.getTicks().setReverse(true);
		
axis2.getTicks().setCallback(new TickCallback() {
	
	@Override
	public String onCallback(AbstractChart<?, ?> chart, TickItem item) {
		List<Dataset> dss = chart.getData().getDatasets();
		Dataset ds = dss.get(item.getIndex());
		return ds.getLabel();
	}
});
```

Then we could add a specific plugin which will add to the canvas the label on right about standing. This plugin is leveraging on new features of Charba to get the info from CHART.JS chart instance about sizing, dimensions and other values.

```java
AbstractPlugin p = new AbstractPlugin() {

	@Override
	public String getId() {
		return "standings";
	}

	/* (non-Javadoc)
	 * @see org.pepstock.charba.client.plugins.AbstractPlugin#onAfterDatasetsDraw(org.pepstock.charba.client.AbstractChart, double)
	 */
	@Override
	public void onAfterDatasetsDraw(AbstractChart<?, ?> chart, double easing, JavaScriptObject options) {
		final int padding = 30;
		final int datasetsCount = chart.getData().getDatasets().size();
		Context2d ctx = chart.getCanvas().getContext2d();

		ScaleItem scaleX = chart.getChartNode().getScales().getItems().get(ScalesNode.DEFAULT_X_AXIS_ID);
		ScaleItem scaleY = chart.getChartNode().getScales().getItems().get(ScalesNode.DEFAULT_Y_AXIS_ID);
				
		int heightAmongLabels = (scaleY.getBottom() - scaleY.getTop()) / (datasetsCount-1);

		int x = scaleX.getRight() + padding;
		int y = scaleY.getTop();
		for (int i=0; i<datasetsCount; i++) {
			int index = i + 1;
			ctx.setFillStyle("rgb(0, 0, 0)");
			ctx.setFont("22px bold Helvetica Neue");
			ctx.setTextAlign(TextAlign.CENTER);
			ctx.setTextBaseline(TextBaseline.MIDDLE);
			ctx.fillText(String.valueOf(index), x, y);
			y = y + heightAmongLabels;
		}
	}
};
try {
	chart.getPlugins().add(p);
} catch (InvalidPluginIdException e) {
	// exception
}
```

Here is a temporary version of Charba 1.5. 

[charba-1.5.zip](https://github.com/pepstock-org/Charba/files/2319093/charba-1.5.zip)
