### ISSUE TITLE
Error when desselect all line datasets

### ISSUE THREAD

**Issue by rodrigobastosv** [pepstock-org/Charba#12]
When all the datasets are unselected, the chart breaks the exibithion like is shown on the image. Is there a solution or workaround for it?

![a](https://user-images.githubusercontent.com/12686272/44480919-db18db80-a61a-11e8-9a42-cff3c34f4aaf.png)

**Comment by stockiNail** [comment]
@rodrigobastosv it's an issue related to the precision of doubles.

Here is the source code to format the ticks when all datasets are hidden. This is the workaround.
You should add a TICK callback in order to format the ticks.

```java
axis2.getTicks().setCallback(new TickCallback() {
	
	private final NumberFormat FORMAT = NumberFormat.getFormat("0.0");
	
	@Override
	public String onCallback(AbstractChart<?, ?> chart, TickItem item) {
		boolean allHidden = false;
		List<Dataset> dss = chart.getData().getDatasets();
		for (int i=0; i<dss.size(); i++){
			DatasetMetaItem metadata = chart.getDatasetMeta(i);
			if (metadata != null) {
				allHidden = allHidden || metadata.isHidden();
			}
		}
		if (allHidden) {
			return FORMAT.format(item.getValue());
		}
		return String.valueOf(item.getValue());
	}
});
```

Another  workaround is to disable to the user the possibilityt to hide all datasets but at least 1 must be displayed.

Testing that, I have found 1 bug (thank you!!) therefore if you want to use it, please wait next release.

Here is the code how to do it.

```java
chart.addHandler(new LegendClickEventHandler() {
			
	@Override
	public void onClick(LegendClickEvent event) {
		AbstractChart<?, ?> chart = event.getChart();
		DatasetMetaItem metadata = chart.getDatasetMeta(event.getItem().getDatasetIndex());
		if (metadata.isHidden()) {
			metadata.setHidden(false);
		} else {
			int count = 0;
			List<Dataset> dss = chart.getData().getDatasets();
			for (int i=0; i<dss.size(); i++){
				DatasetMetaItem metadataItem = chart.getDatasetMeta(i);
				if (!metadataItem.isHidden()) {
					count++;
				}
			}
			if (count > 1) {
				metadata.setHidden(true);
			} else {
				return;
			}
		}
		chart.update();
	}
}, LegendClickEvent.TYPE);
```

**Comment by rodrigobastosv** [comment]
Thank you @stockiNail . That worked like a charm!

**Comment by stockiNail** [comment]
@rodrigobastosv FINE!

**Comment by stockiNail** [comment]
@rodrigobastosv FYI in the new version 1.5, there is the class which implements what I wrote here to fix the number format. The class is [org.pepstock.charba.client.callbacks.impl.NoSelectedDatasetTicksCallback ](https://github.com/pepstock-org/Charba/blob/master/src/org/pepstock/charba/client/callbacks/impl/NoSelectedDatasetTicksCallback.java) and it will be maintained.

Her is how to use it:

```java

axis.getTicks().setCallback(new NoSelectedDatasetTicksCallback());

```

Also the legend click handler to disable that all datasets will be hidden has been added to Charba and it will be maintained. The  class is [org.pepstock.charba.client.callbacks.impl.AtLeastOneDatasetHandler](https://github.com/pepstock-org/Charba/blob/master/src/org/pepstock/charba/client/callbacks/impl/AtLeastOneDatasetHandler.java).

Her is how to use it:

```java

chart.addHandler(new AtLeastOneDatasetHandler(), LegendClickEvent.TYPE);

```
