### ISSUE TITLE
MaintainRatio and Mobile

### ISSUE THREAD

**Issue by nseb** [pepstock-org/Charba#13]
I use maintainRatio to have a fairly consistent HMI, in some cases this is not enough, and setter the heigth pixel a little annoying depending on the size of the viewport. 
It's would be possible to have in addition to the property maintainRatio, a ratioFactor to determine the height according to the width, today by default, it's 1/2

![image](https://user-images.githubusercontent.com/6363226/45481264-62093180-b74b-11e8-89e1-4c01d5a96e43.png)

**Comment by stockiNail** [comment]
uhm... it sounds an enhancement for CHART.JS. Otherwise you should set height pixel, depending on width at runtime by a plugin...

**Comment by nseb** [comment]
Yes , 8px

**Comment by nseb** [comment]
@stockiNail  , Yes !

**Comment by nseb** [comment]
@stockiNail , thanks for your reply 
For Ratio,  I will try the option with the plugin

**Comment by stockiNail** [comment]
@nseb Under teh review we are doing, I see that CHART.JS added new property `aspectRatio`:

| Name | Type | Default | Description
| ---- | ---- | ------- | -----------
| `aspectRatio` | `Number` | `2` | Canvas aspect ratio (i.e. `width / height`, a value of 1 representing a square canvas). Note that this option is ignored if the height is explicitly defined either as attribute or via the style.

This is new and it's missing in Charba. We will implement soon.

**Comment by stockiNail** [comment]
@nseb  added new property.

Here is part of the code:

```java
chart.getOptions().setResponsive(true);
chart.getOptions().setMaintainAspectRatio(true);
chart.getOptions().setAspectRatio(3);
```

Here is the picture (w: 1539, h:513):
![aspectratio](https://user-images.githubusercontent.com/11741250/49390423-36359080-f729-11e8-8992-aed21a333378.png)

The aspect ratio is also maintained during the resize.
We are preparing the new version 1.7.

**Comment by stockiNail** [comment]
Charba [1.7](https://github.com/pepstock-org/Charba/releases/tag/1.7) released
