### ISSUE TITLE
Add Extra Information in CategoryAxis

### ISSUE THREAD

**Issue by nseb** [pepstock-org/Charba#17]
Hi,

I would add extra information(weather) in Time Axis like this chart :
![image](https://user-images.githubusercontent.com/6363226/48940922-a0745700-ef19-11e8-94e1-8c4a945f0b6f.png)

It's possible with plugin ?

**Comment by stockiNail** [comment]
@nseb the use case is similar of flags into chart, issue #10 

Yes, with plugin is possible or also by controller (a little bit more complex). Of course, you must be familiar with Canvas/[Context2D](http://www.gwtproject.org/javadoc/latest/com/google/gwt/canvas/dom/client/Context2d.html) API and their limitations

**Comment by stockiNail** [comment]
This [link](http://docs.w3cub.com/dom/canvas_api/drawing_dom_objects_into_a_canvas/) shows how to add DOM objects to a canvas. You should implement some wrappers in GWT.
Maybe can help

**Comment by stockiNail** [comment]
@nseb sorry for long time for this reply.

We have created an utility to add HTML code as Image on a canvas. The result below is a result of a plugin and this new utility.

What do you think (we didn't spend time on graphics, it could be better)?

![raster](https://user-images.githubusercontent.com/11741250/52863651-b79d9c00-3138-11e9-89fc-d6b896ac8781.png)

**Comment by nseb** [comment]
@stockiNail  , sorry for my late response , that's exactly what I want to do.
You have a example code ?

**Comment by stockiNail** [comment]
@nseb Yes, see [here](https://github.com/pepstock-org/Charba-Showcase/blob/master/src/org/pepstock/charba/showcase/client/samples/jsinterop/HTMLAnnnotationView.java).

But this works only by new feature of Charba, AnnotationBuilder, that will be released with Charba version 2.1. The wiki, javadoc and showcase are already aligned with new version and we are going to release it in next weeks.

Honestly, we would wait for new CHART.js version (where they will fix the code using gradient), Datalabels plugin (same issue)

If you are interested, this is the list of new features version 2.1:

 * new `Pattern` implementation for dataset 
 * new `Gradient` implementation for dataset
 * full implementation of [DataLabels](https://github.com/chartjs/chartjs-plugin-datalabels) plugin included as Charba component  
 * full implementation of [Labels](https://github.com/emn178/chartjs-plugin-labels) plugin included as Charba component
 * new [DataLabels](https://github.com/chartjs/chartjs-plugin-datalabels) plugin callbacks provided out-of-the-box
 * full implementation of filling mode
 * new AnnotationBuilder utility to add HTML code on chart and its canvas.
 * chart background color plugin accepts `Pattern` and `Gradient`
 * replace invalid plugin id and controller type exception with illegal argument exception
 * new charts lifecycle listeners
 * added replacer function into `JSON` utility 
 * added `stringifyWithReplacer` methods to `JSON` utility with out-of-the-box replacer to avoid `TypeError cycle object`
 * added `dir` and `dirxml` methods in `Console` utility
 * set images as point styles at all levels

**Comment by stockiNail** [comment]
solved by version 2.1
