### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by cRUSHER-HLG** [pepstock-org/Charba#18]
My Problem is i want to add your lib into an existing project but when i do this i become this error all the times: [ERROR] Unable to find 'org/pepstock/charba/Charba.gwt.xml'.

What i have done:
- Installed with maven: Build Successfully
- inherated successfully
- found by spring to access them in the ...View classes.

On every page reload when the page compiles new it shows me this error that i gave you.

I dont know how to resolve the error or what i need to do.

**Comment by Fuzzo** [comment]
It looks like the charba-1.x.jar file is not in the WEB-INF/lib directory of your application. 
Please ensure it is in the right place and, as the wiki says, put the following line in your GWT module file (yourapp.gwt.xml):
`<inherits name="org.pepstock.charba.Charba"/>`

**Comment by cRUSHER-HLG** [comment]
After i have put the jar into the webinf folder it works correctly. Thank you man 🍡
