### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cRUSHER-HLG** [pepstock-org/Charba#19]
Is it possible to add these things also with the precentage amount on the side:

And also this to write the amounts over the barcharts?

**Comment by stockiNail** [comment]
@cRUSHER-HLG first of all, what you need must be done by a plugin.

There is a CHART.JS plugin ([pieceLabel](https://github.com/emn178/Chart.PieceLabel.js/)) that you can use in your project. See Charba wiki [here](https://github.com/pepstock-org/Charba/wiki/Plugins#importing-existing-chartjs-plugins) and see the thread #1 . A sample in Charba showcase project [here](https://github.com/pepstock-org/Charba-Showcase/blob/master/src/org/pepstock/charba/showcase/client/samples/PieceLabelView.java).

Furthermore for BAR chart, in Charba showcase project there is the same sample of CHART.JS, which add values on top of bar, as you want. See [here](https://github.com/pepstock-org/Charba-Showcase/blob/master/src/org/pepstock/charba/showcase/client/samples/VerticalBarPluginLabelView.java) the source code and here the [showcase](http://www.pepstock.org/Charba-Showcase/Charba_Showcase.html).

Here the picture:
![barlabels](https://user-images.githubusercontent.com/11741250/49276424-cb612c80-f47e-11e8-90e7-b2b0c2653b0e.png)

**Comment by cRUSHER-HLG** [comment]
Which fonttype is in use for the left labels to make the numbers look like the left labels?

**Comment by stockiNail** [comment]
The font info (fontSize, fontStyle, fontColor, fontFamily) are retrievable by

`axis.getTicks().getFont..();` 

and then you could applied the same to the plugin.

**Comment by cRUSHER-HLG** [comment]
thanks

**Comment by cRUSHER-HLG** [comment]
Another question if i can access the left legend that you draw that has the values from -40 to 100?

**Comment by cRUSHER-HLG** [comment]
okey i found it: https://github.com/pepstock-org/Charba-Showcase/blob/master/src/org/pepstock/charba/showcase/client/samples/StepSizeView.java
