### ISSUE TITLE
Found Bug

### ISSUE THREAD

**Issue by cRUSHER-HLG** [pepstock-org/Charba#20]
I found a bug when you have a BarChart chart:
if we have activate this option and we have a value that is exact the same as the left side values it displays it as 100%.
chart.getOptions().setResponsive(true);

If you set it to false the the chart set it right. With this i mean if you have the highest barchart entry by 50 the chart set the left label to 60 but when its true it keeps it to 50.
chart.getOptions().setResponsive(false);

**Comment by stockiNail** [comment]
@cRUSHER-HLG have you solved the issue? I have seen you closed this issue

**Comment by stockiNail** [comment]
@cRUSHER-HLG  I did some tests.
Max Tick: **80**
Max value of data in dataset: **80**

`chart.getOptions().setResponsive(true);`

![resp-yes](https://user-images.githubusercontent.com/11741250/49315323-917b3f00-f4ed-11e8-9e6a-1802c0375d45.png)

`chart.getOptions().setResponsive(false);`

![resp-no](https://user-images.githubusercontent.com/11741250/49315344-a5bf3c00-f4ed-11e8-865a-3e0f018a5534.png)

The max value of the ticks is the same of max value of data of dataset.
