### ISSUE TITLE
How can I use Charba for chart drilldown or range selection?

### ISSUE THREAD

**Issue by Eljah** [pepstock-org/Charba#21]
Or at least handle any events on the chart say to get the ajax data and so on? Unfortunately no such examples in the demo.

**Comment by stockiNail** [comment]
Drill down or range selection are not implemented ootb. There is a plugin of Chart.js to zoom if you want to try it.
About events, [here]( https://github.com/pepstock-org/Charba-Showcase/blob/master/src/org/pepstock/charba/showcase/client/samples/DatasetSelectionView.java) is the source code for dataset selection and in the wiki you can see how to use events. See [here](https://github.com/pepstock-org/Charba/wiki/General#events).

**Comment by Eljah** [comment]
@stockiNail yes, that is one of the features I'm looking for!
Once more required is to set on the main graph the vertical stick at some point and another vertical stick on another and on the second stick set up to call the Ajax to reload the graph to the drilled down detailed view. I have briefly understood the idea how to do it with onClick handlers, but not yet hot to drow sticks onto clicked items or highlight mask as in the smaller graph below in your example.  So if you have this example to be added to the showcase, that would be best for me!

**Comment by Eljah** [comment]
@stockiNail exactly! for point 4 the specific handler for this whole event would be the perfect thing, just to call the ajax to reload the dataset with smaller range (but potentially a new points initially not present, because the timeseries in the storage might be populated with data from the past) or do some more actions to design.

Another question is related to the plugin: does the jar file of the core Charba can contain the plugin js? If not, is it possible to build the "Chart Js and all plugins edition" Charba? For the certain reason to provide the compatible versions of the plugins and core ChartJS (as Spring boot does for the Spring dependencies).

**Comment by stockiNail** [comment]
@Eljah Charba is coming with Chart.JS bundle. None other parts (plugins or others) is added out of the box.
I'm not sure if it could be a good idea to import all plugins. 
I'd prefer that who needs a specific one, will include it (using the guide how to do it).

**Comment by stockiNail** [comment]
@Eljah this is what we implemented and still testing.

A selection on a chart will be implemented by a plugin (will be provided as part of CHARBA) and you can received the event of end selection adding an handler to a chart. 

```java
try {
	small.getPlugins().add(new DatasetsSelector());
} catch (InvalidPluginIdException e) {
	e.printStackTrace();
}
		
small.addHandler(new DatasetRangeSelectionEventHandler() {
			
	@Override
	public void onSelect(DatasetRangeSelectionEvent event) {
		StringBuilder sb = new StringBuilder();
		sb.append("Dataset from: <b>").append(event.getFrom()).append("</b><br>");
		sb.append("Dataset to: <b>").append(event.getTo()).append("</b><br>");
		new Toast("Dataset Range Selected!", sb.toString()).show();
		List<DataPoint> points = dataset1.getDataPoints();
		Date min = points.get(event.getFrom()).getT();
		Date max = points.get(event.getTo()).getT();
                axis.getTime().setMin(min);
		axis.getTime().setMax(max);
		chart.draw();
	}
}, DatasetRangeSelectionEvent.TYPE); 
```
Here is the result:

![selection](https://user-images.githubusercontent.com/11741250/50017530-a3b8ab00-ffcc-11e8-8c90-fdf84e83b9c5.png)


About this example, some notes:

 1. The view contains 2 charts: the chart on top shows the selection of bottom one. The plugin is added to the bottom one.
 2. The plugin calls  `chart.draw()` because we are setting MIN e MAX on the axis and, to apply the updates, redraw is mandatory.

What is still missing or constraints on the code ?

1. currently works only for  `line` chart. The support for `bar` is under development. No other chart type will be supported.
2. Defaults are not set yet. 
3. The plugin options to add to chart one (see [here](https://github.com/pepstock-org/Charba/wiki/Plugins#options)), where the user could set the selection color and axis ID
4. The plugin will disable Tooltips to avoid conflicts with mouse events **(constraint)**
5. The resize of chart must maintain the selection 
6. disable Canvas object selection at browser level, by `preventDefault() `

This is just feedback about what we are doing and hopefuliy is what you are looking for.

**Comment by Eljah** [comment]
@stockiNail thanks for going ahead with that! for some reason I can't take it right now to test around my chart features, but it looks promising so I'l be glad to try it as it will be stabilized!

**Comment by Eljah** [comment]
And I'm really happy that the plugin will be shipped together with Charba! I like uniform js dependencies being packed really as dependencies, i.e. jars used in gwt client, webjars for jsps, no js files scattered over resource folder with own versions etc.

**Comment by Eljah** [comment]
@stockiNail one more idea I think being very widely used use case, is to provide out-of-the box 4 buttons and the handlers for them for expanding the visible area of the detailed subrange and the total range back and forward in the timeline. For the subrange if would be just a zoom in with picking up the main chart's data right or left to initially selected, in the man range a developer may do an ajax request to append its initial data to make them more full back or forward along the timeline. This kind of features are widely used in many timeseries viewing systems, so it would be very useful to have in in Charba at least with plugin shipped with it. As those controls are really better when they are the part of the chart, not something put all together by the developer that integrates the chart inside the page.

**Comment by stockiNail** [comment]
@Eljah got it even if, let me say in advance, what you are looking for it's not so simple. Be aware that Charba is "just" a wrapper of Chart.js which has full control on chart drawing. But let me think more about your idea. 
In the meanwhile, about the previous pending open items, only the first one is under development (bar chart) and only for a specific case (time series).

**Comment by stockiNail** [comment]
@Eljah the plugin has been completed and tested. We are going to merge into master and publish into new version asap.
If you're interested, [here](https://github.com/pepstock-org/Charba/blob/stock/src/org/pepstock/charba/client/plugins/impl/DatasetsItemsSelector.java) is the source code of the plugin (into stock branch)

**Comment by stockiNail** [comment]
@Eljah FYI I've prepared a sample but based on Charba 2 (jsinterop complaint).

You have 1 chart (time series, data on day)

![day](https://user-images.githubusercontent.com/11741250/51263711-1a263f80-19b5-11e9-930b-9edea803bb22.png)

Selecting on chart

![select](https://user-images.githubusercontent.com/11741250/51263745-2c07e280-19b5-11e9-8789-50c682809f0a.png)

you will drill down having the data among selected period in minute

![hour](https://user-images.githubusercontent.com/11741250/51263788-40e47600-19b5-11e9-9059-33fd6968995e.png)

The button "back" enables to go back to day chart.

**Comment by Eljah** [comment]
Hi @stockiNail , it looks perfect! For now Charba is 1.7, when do you plan Charba 2 being available?

**Comment by Eljah** [comment]
Have you added the previous version, based on the plugin, to the http://www.pepstock.org/Charba-Showcase/Charba_Showcase.html ?

**Comment by stockiNail** [comment]
@Eljah we are completing testing and we are going to deploy new version 2.0 in next days. Sorry but the refactoring, to leave JSNI for going to JSINTEROP was quite time consuming.

About Showcases, is aligned on version 1.7 but the plugin is not included. It will update together with version 2.0.

[WIKI](https://github.com/pepstock-org/Charba/wiki) 2.0 is already published. You can have a look to the plugin usage description, we created a dedicated page, [here](https://github.com/pepstock-org/Charba/wiki/PluginDatasetsItemsSelector). In that page there is also the link to source code of main part of plugin.

**Comment by stockiNail** [comment]
@Eljah we have published the [showcase](http://www.pepstock.org/Charba-Showcase/Charba_Showcase.html) of version 2.0.
To see the drill down, go to "Time series charts" --> "Drill down".
To see the range selection, go to "Time series charts" --> "Zooming".

**Comment by stockiNail** [comment]
@Eljah [Version 2.0](https://github.com/pepstock-org/Charba/releases/tag/2.0) has been released. Next week jars will published into MVN

**Comment by stockiNail** [comment]
@Eljah version 2.1 has been released. About this issue, have a look to [selector plugin](https://github.com/pepstock-org/Charba/wiki/PluginDatasetsItemsSelector) features. I think we should have more or less everything.
