### ISSUE TITLE
Changing options after constructor does not work

### ISSUE THREAD

**Issue by jake1164** [pepstock-org/Charba#23]
For instance, if you add:

	@UiHandler("randomize")
	protected void handleRandomize(ClickEvent event) {
                 chart.getOptions().getTitle().setText("new text");
         }
to a click event the title does not change.

Adding chart.update() does not cause the title to change.

Also tried changing title color, etc and nothing changes in the click event (after the constructor).

**Comment by jake1164** [comment]
Great, thanks for the update, I will try the changes shortly.

**Comment by jake1164** [comment]
Works perfect, thanks for the answer!

**Comment by stockiNail** [comment]
@jake1164 we added methods to chart instance in order to update chart, mutating the options property in place.

```java
@UiHandler("randomize")
protected void handleRandomize(ClickEvent event) {
   chart.getOptions().getTitle().setText("new text");
   chart.updateOptions()
}
```

See [updateOptions](https://github.com/pepstock-org/Charba/blob/3a10cae5463f752b446c5571380ce5492db9f059/src/org/pepstock/charba/client/AbstractChart.java#L499)
