### ISSUE TITLE
Problem when using PluginDatasetsItemsSelector plugin

### ISSUE THREAD

**Issue by niekvanderkooy** [pepstock-org/Charba#26]
I am trying to implement the PluginDatasetsItemsSelector plugin by following the wiki as described [https://github.com/pepstock-org/Charba/wiki/PluginDatasetsItemsSelector](here). However, I am getting the bizarre effect that when holding down my left mouse button and moving the mouse, to select an area, the graph seems to redraw multiple times which means all text seems to become "bold":

![Original situation](https://user-images.githubusercontent.com/1261369/52955388-d1372180-338c-11e9-8813-48a51dc2ca39.png)

![First drag](https://user-images.githubusercontent.com/1261369/52955402-d98f5c80-338c-11e9-9443-07ac5b60aeaf.png)

![Multiple drags](https://user-images.githubusercontent.com/1261369/52955412-deeca700-338c-11e9-9121-942ac8a165c7.png)

I have some boilerplate code around the drawing of my charts, so I am not easily able to find a minimal reproducible example to find out what is going wrong. Do you maybe have any idea what might be going on / have you seen this behaviour before?

**Comment by stockiNail** [comment]
@niekvanderkooy The plugin is storing the image of the charts and apply it on canvas when the mouse is moving. This is the only way to draw on the canvas having the selection effect.

The bold effect is due to the above reason but of course it's a bug. It seems it will apply uncorrectly. Let have a look.

**Comment by niekvanderkooy** [comment]
Ah, that makes sense. A workaround of course might be to give the chart a background colour, but since I'm currently relying on the chart having a transparent background I would prefer not to change this.

So if you are able to find the cause of the bug, that would be great! Thanks

**Comment by stockiNail** [comment]
@niekvanderkooy I was asking which background color you are using... but you are faster than me.

Nevertheless this could be a workaround. In my test environment I don't have this behavior even if I think I know what could be....

**Comment by stockiNail** [comment]
@niekvanderkooy I was able to reproduce the issue. I confirm that with background color without transparency works correctly.

**Comment by niekvanderkooy** [comment]
@stockiNail Ah, this time you were faster than me! Indeed, I am now using a background colour as a workaround, and that works.
And you were able to reproduce the bug when using a transparent background?

For the time being the workaround is find, and if you are able to fix the bug in due course it would be much appreciated.

**Comment by stockiNail** [comment]
@niekvanderkooy yes, I have got the bug with transparent background. Now I'm looking for a final solution (could be to clean canvas and reapply the image)

**Comment by stockiNail** [comment]
@niekvanderkooy I fixed the issue, cleaning the canvas before applying the stored image on it. 

In this way it doesn't take care about the background color because it applies the images on clean canvas every time. If not urgent, I'd like to deploy it with new version 2.1 (almost ready), otherwise I'll give the jar file in advance.

**Comment by niekvanderkooy** [comment]
Great, thanks so much!
It's fine for me to wait until the 2.1.

**Comment by stockiNail** [comment]
@niekvanderkooy tagged new version [2.1](https://github.com/pepstock-org/Charba/releases/tag/2.1), fixing this issue. In the next days it will be available on MVN as well
