### ISSUE TITLE
Automatically set x-axis max in a scatter-linechart

### ISSUE THREAD

**Issue by niekvanderkooy** [pepstock-org/Charba#3]
Say I have the following bit of code:
```
        LineChart chart = new LineChart();

        LineDataset dataset = new LineDataset();

        DataPoint dp1 = new DataPoint();
        dp1.setX(0); dp1.setY(20);

        DataPoint dp2 = new DataPoint();
        dp2.setX(1); dp2.setY(30);

        DataPoint dp3 = new DataPoint();
        dp3.setX(2); dp3.setY(40);

        dataset.setDataPoints(dp1, dp2, dp3);

        chart.getData().setDatasets(dataset);

        return chart;
```

When I draw this chart, the y-axis is automatically scaled for the datapoints to fit on it (In this example, from 20 to 40). However, the x-axis is not: this seems to always go from 0 to 1.

I can fix this by adding:
```
        Axis axis = new CartesianLinearAxis(chart);
        ((CartesianLinearAxis) axis).getTicks().setMin(0);
        ((CartesianLinearAxis) axis).getTicks().setMax(2);

        chart.getOptions().getScales().setXAxes(axis);
```

My question is however: is it by design that the y-axis automatically scales, and the x-axis does not? Or is there a way to make the x-axis scale automatically?
Having this option would prevent us having to manually keep track of the "lowest" and "highest" x-value, and afterwards creating a new axis just to be able to properly scale.

**Comment by stockiNail** [comment]
@niekvanderkooy y-axis and x-axis scale automatically. Creating own axes you can change behaviors.

About your example, be aware the DataPoints can be used in Line or Bar charts when you want to use TimeSeries.
Instead, Bubble or Scatter charts are based on DataPoints.

Seeing the example, I think you could:

 1. Scatter chart when the points are what you set.  In your sample, change LineChart and LineDataset into ScatterChart and ScatterDataset
 2. Line chart but don't use DataPoints but "labels" and "data":
 
```java
LineChart chart = new LineChart();

LineDataset dataset = new LineDataset();
// set data
dataset.setData(20, 30, 40);
// set labels
chart.getData().setLabels("0", "1", "2");
chart.getData().setDatasets(dataset);
```

**Comment by stockiNail** [comment]
@niekvanderkooy Thank you for clarification.

A scatter chart is a line chart with the difference that by default the "showLines" is set to false.

Nevertheless the Scatter options allow you to set this value:

```java
ScatterChart chart = new ScatterChart();

chart.getOptions().setShowLines(true);

ScatterDataset dataset = new ScatterDataset();

DataPoint dp1 = new DataPoint();
dp1.setX(0); dp1.setY(20);

DataPoint dp2 = new DataPoint();
dp2.setX(1); dp2.setY(30);

DataPoint dp3 = new DataPoint();
dp3.setX(2); dp3.setY(40);

dataset.setDataPoints(dp1, dp2, dp3);

chart.getData().setDatasets(dataset);

return chart;
```

Here is the result:

![bug3](https://user-images.githubusercontent.com/11741250/40054319-b994abd4-5844-11e8-8096-1522ff477022.png)

Does that look like what you need?

**Comment by stockiNail** [comment]
@niekvanderkooy About time series, see the [Charba Showcase](http://www.pepstock.org/Charba-Showcase/Charba_Showcase.html), select "Time series charts".

Bar TimeSeries sample, see [here](https://github.com/pepstock-org/Charba-Showcase/blob/master/src/org/pepstock/charba/showcase/client/samples/TimeSeriesBarView.java).
Line TimeSeries sample, see [here](https://github.com/pepstock-org/Charba-Showcase/blob/master/src/org/pepstock/charba/showcase/client/samples/TimeSeriesView.java).

The Charba wiki is still under construnction (sorry!).

**Comment by niekvanderkooy** [comment]
Ah, this indeed does what I was looking for, thanks!
I think I was confused due to the ScatterDataset also having a setShowLines option, which is always forced to false. I did not realise I could also achieve the showing of a line through the ScatterOptions.

Thanks for your help!
