### ISSUE TITLE
Extension DataLabels

### ISSUE THREAD

**Issue by ak80** [pepstock-org/Charba#31]
Hello,

I would like to use the DataLabels extension on a doughnut chart, as seen in the showcase. I copied the code from [DataLabelsDoughnutView.java](https://github.com/pepstock-org/Charba-Showcase/blob/2.1/src/org/pepstock/charba/showcase/client/samples/jsinterop/DataLabelsDoughnutView.java) but get no data labels.

Do I need to load/configure the plugin somehow?

I am using charba 2.1

Thank you for any pointers in the right direction!

**Comment by stockiNail** [comment]
@ak80 I have the feeling you didn't enable the plugin because the showcase it's into DemoView class (entry point). See [Wiki](https://github.com/pepstock-org/Charba/wiki/DataLabels#activation).

Add to your entry point the following:

```java
DataLabelsPlugin.enable();
```

Let me know if works
