### ISSUE TITLE
Dynamic Label Steps

### ISSUE THREAD

**Issue by cRUSHER-HLG** [pepstock-org/Charba#32]
Hello,

When we add data to an barchart the data is always double. My problem is that the legend on the left side shows also the values in double but i want these values as integer. how can i assume this?
As second how to begin the left legend from 0?

**Comment by cRUSHER-HLG** [comment]
When i use setResponsive(false); then it shows the values on the left legend only as integer but it gets little. by setResponsive(true); its the full size of XS_5 / LG_5

**Comment by stockiNail** [comment]
@cRUSHER-HLG do you have a screenshot to share? And some pieces of code about chart config options?

**Comment by cRUSHER-HLG** [comment]
Okey works now. The configs are the default once. 
The step that solved this problem for me:
Double.parseDouble(NumberFormat.getFormat("0").format(buffer[i]));

**Comment by stockiNail** [comment]
FINE! But let me ask you: when you wrote "legend" you meant "legend" or "axes"?
Because on Axes you have ticks config and callbacks to do that
