### ISSUE TITLE
Invalid POM version 2.2 published into MVN

### ISSUE THREAD

**Issue by stockiNail** [pepstock-org/Charba#33]
Due to an error into ivy.xml (version) it's not possible to used version 2.2 by MVN repo.

Underevaluation

**Comment by Fuzzo** [comment]
Working on it... the aim is to overwrite the current wrong POM file with the fixed one if possible, otherwise we'll increase the version number.

**Comment by stockiNail** [comment]
Published new version [2.3](https://github.com/pepstock-org/Charba/releases/tag/2.3) to solve this issue
