### ISSUE TITLE
 Resource js/chartjs-plugin-datalabels.min.js missing from release files

### ISSUE THREAD

**Issue by jake1164** [pepstock-org/Charba#37]
Using the Zip file of the releases (2.5, 2.4, 2.3) all compile with the error:
 Resource js/chartjs-plugin-datalabels.min.js not found.

Looking in the 2.1 release .zip file in the Charba-2.1/src/org/pepstock/charba/client/resources/js directory contains: 
charba.helper.js			chart.bundle.min.js			chartjs-plugin-labels.min.js
charba.helper.min.js			chartjs-plugin-datalabels.min.js

Looking in the 2.5 release .zip file the same folder has: 
charba.helper.js		chartjs-plugin-labels.js

**Comment by jake1164** [comment]
Looking in the 2.4 .jar file the resource/js folder contains:
charba.helper.min.js			chartjs-plugin-datalabels.min.js
chart.bundle.min.js			chartjs-plugin-labels.min.js

**Comment by stockiNail** [comment]
@jake1164 The "external" JS resources (not manage by us) are moved out of the src folder.
Those JS resources are located into folder [/resources](https://github.com/pepstock-org/Charba/tree/master/resources) and inside the build, those files are copied into the right folder before jaring the project.

 Those files are created by GitHub. I suggest you to clone the project.

**Comment by jake1164** [comment]
Ok, not the most elegant solution, however, I will have to move the files and zip from /resources to the .js folder listed on the tagged release.

**Comment by stockiNail** [comment]
@jake1164 no, I don't have because this is done by build.xml invoking ANT. I wouldn't do anything.

The only thing is that the "Sources" files don't contain those resources but build it, the result (JAR files) contains everything you need.

**Comment by stockiNail** [comment]
>  I will have to move the files and zip from /resources to the .js folder listed on the tagged release.

Maybe I misunderstood your need (apologize) but I can not understand why you should move and zip the files if they are already into JAR (ready to use).

**Comment by jake1164** [comment]
We are required by policy to review any 3rd party code we use, thus, we are not able to just a .jar file that we have not compiled (via our build system) ourselves. So we take the released code (the release zip), move it into our system, which extracts it, scans the code and then compiles it into a new jar file.

**Comment by stockiNail** [comment]
Thank you, now it's clear. Could be helpful if I will add another ZIP file with all sources (java, js, XML and so on) and publish into the releases page, with a specific name?? But not the ZIP created out of the box by GitHub. 
This is something that I can easily do.

About why we moved out.. Those JS are already minified and we don't touch them. For this reason we decided to move out from SRC folder.  
Let me know

**Comment by jake1164** [comment]
Fully can understand about not wanting to intermingle code.  

If you can create a new release that would be great, perhaps charba-2.5-sources.zip  or something along those lines?

**Comment by stockiNail** [comment]
Yes, let me take time. ASAP I'll publish it.

**Comment by stockiNail** [comment]
Done! Please check if it's ok. It's published into [release page 2.5](https://github.com/pepstock-org/Charba/releases/tag/2.5), [here](https://github.com/pepstock-org/Charba/releases/download/2.5/charba-2.5-sources.zip)

In the next version, it will be present when new release will be published.

Let me know

**Comment by jake1164** [comment]
Thanks for the quick turnaround, I will throw this on the queue and let you know tomorrow morning.

**Comment by jake1164** [comment]
This is resolved from my side.  Thanks again!

**Comment by stockiNail** [comment]
@jake1164 very good!

Be aware that if you are gonna use a not tagged release (cloned from `master`) and you have to do the same internal check, run ANT `build.xml`, target `build-all` which will create all files for MVN (+ new zip source file), always into `dist` folder
