### ISSUE TITLE
Maximum value of Y-axis

### ISSUE THREAD

**Issue by lightingft** [pepstock-org/Charba#38]
Is it possible to get the current maximum value of the y-axis of a Chart without doing calculations on the data itself? For instance, taking the very first Line Chart example from the wiki:
https://github.com/pepstock-org/Charba/wiki/ChartLine

So the max value is y = 100 on the Y axis. Is it possible to get this number?

**Comment by stockiNail** [comment]
@lightingft you should create a [CartesianLinearAxis](https://github.com/pepstock-org/Charba/wiki/CartesianLinearAxes), configure the max ticks and set it to your chart. See the example here into [showcase repo](https://github.com/pepstock-org/Charba-Showcase/blob/master/src/org/pepstock/charba/showcase/client/samples/jsinterop/MinMaxView.java) and live [here](http://www.pepstock.org/Charba-Showcase/Charba_Showcase.html), in the folder "Miscellaneous", "Min Max" item.

Here is part of source code anyway

```java
CartesianLinearAxis axis = new CartesianLinearAxis(chart);
axis.setDisplay(true);
axis.getTicks().setMin(20);
axis.getTicks().setMax(80);
		
chart.getOptions().getScales().setYAxes(axis);
```
 Here is the result:

![minMax](https://user-images.githubusercontent.com/11741250/59299633-6b4d0d80-8c8d-11e9-9ac4-1562ce865418.png)

**Comment by stockiNail** [comment]
@lightingft if you need the max value of the axis, you should access to chart node, as following:

```java
if (chart.isInitialized()){
     // internal chart entities
     ChartNode node = chart.getNode();
     // gets scales
     ScalesNode scales = node.getScales();
     // gets sclaes map
     Map<String,ScaleItem> scalesMap = scales.getItems();
     // gets the Y axis
     ScaleItem item = scalesMap.get(Scales.DEFAULT_Y_AXIS_ID);
     // gets max
     int max= item.getMax();
}
```

**Comment by stockiNail** [comment]
@lightingft be aware that the previous source code is providing you the MAX value of axis, NOT the max value of your data.

To have it, you could use `Collections.max(Collection, Comparator)`.

**Comment by lightingft** [comment]
> @lightingft if you need the max value of the axis, you should access to chart node, as following:
> 
> ```java
> if (chart.isInitialized()){
>      // internal chart entities
>      ChartNode node = chart.getNode();
>      // gets scales
>      ScalesNode scales = node.getScales();
>      // gets sclaes map
>      Map<String,ScaleItem> scalesMap = scales.getItems();
>      // gets the Y axis
>      ScaleItem item = scalesMap.get(Scales.DEFAULT_Y_AXIS_ID);
>      // gets max
>      int max= item.getMax();
> }
> ```

Hmm, strangely the key that I had to use (without changing anything) for scalesMap had to be "y-axis-1" instead of the Default Y Axis ID ("y-axis-0").

Thank you for the answer!

**Comment by stockiNail** [comment]
> Hmm, strangely the key that I had to use (without changing anything) for scalesMap had to be "y-axis-1" instead of the Default Y Axis ID ("y-axis-0").

I see that if you are using Scatter charts, CHART.JS is setting as default Axis id `[x-axis-1, y-axis-1]`
Nevertheless you can set ID of axis, using own linear axis instance, like this (tested with a scatter chart):

```java
CartesianLinearAxis axis = new CartesianLinearAxis(chart);
axis.setDisplay(true);
axis.setId(Scales.DEFAULT_Y_AXIS_ID);
chart.getOptions().getScales().setYAxes(axis);
```

**Comment by lightingft** [comment]
> > Hmm, strangely the key that I had to use (without changing anything) for scalesMap had to be "y-axis-1" instead of the Default Y Axis ID ("y-axis-0").
> 
> I see that if you are using Scatter charts, CHART.JS is setting as default Axis id `[x-axis-1, y-axis-1]`
> Nevertheless you can set ID of axis, using own linear axis instance, like this (tested with a scatter chart):
> 
> ```java
> CartesianLinearAxis axis = new CartesianLinearAxis(chart);
> axis.setDisplay(true);
> axis.setId(Scales.DEFAULT_Y_AXIS_ID);
> chart.getOptions().getScales().setYAxes(axis);
> ```

Ahh, I see. Thanks! That answers my problem.

**Comment by stockiNail** [comment]
@lightingft I was curious why the scatter charts are using y-axis-1 instead of 0.

I have seen that the default scales definitions (default set by CHART.JS) of Scatter chart have got x-axis-1 and y-axis-1. 

In Charba that could see them as following, going into the defaults for every chart type (that you can change as well):

```java
Defaults.get().getOptions(ChartType.SCATTER).getScales().getYAxes();
```
