### ISSUE TITLE
DataSelector not working

### ISSUE THREAD

**Issue by SandraK82** [pepstock-org/Charba#39]
The Charba-Showcase featurs under "Time series Charts"->"Zooming" a nice example of the DataSelector. However i'm completly unable to implement it in my own project. It just does not work, no interaction on the minigraph.
To check what might be wrong, I checked the showcase out, put the Charba-2.5.jar into the project and it does not work, too.

**Comment by stockiNail** [comment]
@SandraK82 let me ask you if the bug is that you are not able to select the area into the chart.

If yes, can you check the GWT compiler options you are using?

**Comment by stockiNail** [comment]
@SandraK82 maybe this is not the root cause of your issue.  I have tested the Showcase and if you don't use `-generateJsInteropExports` as GWT compiler options, you have what I described above: you are not able to select the area.

Have a look to Readme and Wiki:

> Charba version 1.x is based on JSNI method to integrate java script objects.
> Charba version 2.x is based on JSINTEROP method to integrate java script objects.
> JSNI will be removed with GWT 3.
> JsInterop is one of the core features of GWT 2.8.
> Pay attention that GWT compiler (you are using for your project) requires *-generateJsInteropExports* to be passed.

**Comment by SandraK82** [comment]
ah great, this solved it! -> -generateJsInteropExports
Many thank to you!
