### ISSUE TITLE
Reverse Ticks

### ISSUE THREAD

**Issue by nseb** [pepstock-org/Charba#5]
Hello, I am trying to invert the values of my Y axis for a given graph :  
chart.getGlobal().getScale().getTicks().setReverse(true) not working , 
but  Defaults.getGlobal().getScale().getTicks().setReverse(true) working but I do not try to apply to all the grahics of my application

**Comment by stockiNail** [comment]
@nseb the global configuration at chart level is not used to configure it. It's just a merge of CHART.JS configuration used to provide the default values.
To configure a chart you could use Defaults (for all chart instances) or chart itself (see code)

```java
CartesianLinearAxis axis2 = new CartesianLinearAxis(chart);
axis2.setDisplay(true);
axis2.getTicks().setReverse(true);
	
chart.getOptions().getScales().setYAxes(axis2);
```
