### ISSUE TITLE
Add Wrapper for use Color of Gwt Material Design

### ISSUE THREAD

**Issue by nseb** [pepstock-org/Charba#8]
Hi,
it's possible to make a wrapper for use Color defined in GWT Material Design (gwt.material.design.client.constant.Color class) , in Charba instead of hexa/rgb values.
it helps to have graphics with continuity in material style

**Comment by stockiNail** [comment]
@nseb creating a wrapper for GWT material, we will create a dependency with it but Charba could be used also for GWT applications, without material. What we could do is to add the enumeration of GWT material colors into CHARBA.

**Comment by nseb** [comment]
When I said wrapper, I thought a kind of Bridge, the enumeration is perfect.

**Comment by stockiNail** [comment]
@nseb FYI we are developing it. We are also changing all methods to set colors without passing only strings but [IsColor](https://github.com/pepstock-org/Charba/blob/master/src/org/pepstock/charba/client/utils/IsColor.java) objects.

**Comment by stockiNail** [comment]
@nseb Commited in separated branch the GWT material implementation. Here is the source code of [enumeration](https://github.com/pepstock-org/Charba/blob/stock/src/org/pepstock/charba/client/colors/GwtMaterialColor.java) with all [GWT material colors](https://gwtmaterialdesign.github.io/gwt-material-demo/#colors).

Charba has been changed adding new methods to set colors on all components, using [IsColor](https://github.com/pepstock-org/Charba/blob/stock/src/org/pepstock/charba/client/colors/IsColor.java) object.

Here is an sample:

```java
LineDataset dataset1 = chart.newDataset();
dataset1.setLabel("dataset 1");

dataset1.setBackgroundColor(GwtMaterialColor.INDIGO_ACCENT_4);
dataset1.setBorderColor(GwtMaterialColor.INDIGO_ACCENT_4);
dataset1.setData(getRandomDigits(months));
dataset1.setFill(Fill.origin);

LineDataset dataset2 = chart.newDataset();
dataset2.setLabel("dataset 2");

dataset2.setBackgroundColor(GwtMaterialColor.LIGHT_GREEN_ACCENT_2);
dataset2.setBorderColor(GwtMaterialColor.LIGHT_GREEN_ACCENT_2);
dataset2.setData(getRandomDigits(months));
dataset2.setFill(Fill.origin);
```

Here is the result:

![gwtcolors](https://user-images.githubusercontent.com/11741250/41923106-e95458c2-7966-11e8-8b1d-4bea9229acc6.png)

**Comment by nseb** [comment]
Perfect , Thansk a lot. 
Snapshot Jar is available or I have to build the project?

**Comment by stockiNail** [comment]
We haven't published the new version yet.
Tomorrow I'm going to merge in the master.  I'd like to complete some tests in the meantime

**Comment by nseb** [comment]
@stockiNail HI , could you generate a jar even if it's a snapshot ?

**Comment by stockiNail** [comment]
@nseb here it is (called 1.4.1). The file name has been renamed with ZIP ext instead of JAR.

[charba-1.4.1.zip](https://github.com/pepstock-org/Charba/files/2160011/charba-1.4.1.zip)

**Comment by nseb** [comment]
@stockiNail Thanks a lot
